import { isMockApiEnabled, mockDelay } from "@/lib/api/mock";
import type { CreateTokohInput, Tokoh } from "@/types/tokoh";
import { TOKOH_KATEGORI_OPTIONS } from "@/types/tokoh";

// Pola mock service STANDAR (array in-memory, cabang non-mock throw) — sama
// dengan rivalcaleg.ts/saksi.ts/realcount.ts. Tidak ada endpoint/schema apapun
// untuk "Tokoh Masyarakat" (CLAUDE.md Aturan #6) — lihat types/tokoh.ts.
const ENDPOINT_NOT_CONFIRMED =
  "Endpoint Tokoh Masyarakat belum ada — fitur ini masih UI + mock. Aktifkan EXPO_PUBLIC_USE_MOCK_API=true untuk demo.";

// 18 tokoh tersebar di 4 kelurahan yang sama dengan MOCK_DTDOOR/MOCK_TIMSES
// (Cileunyi Kulon/Cinunuk/Cileunyi Wetan/Cimekar, Kec. Cileunyi) — konsisten
// lintas fitur, bukan geografi baru. `alamat`/`pengaruh` ditambah 2026-08-22
// mengikuti context/designs/tokohlist.png.
const MOCK_TOKOH: Tokoh[] = [
  {
    id: 1,
    nama: "KH. Asep Sanusi",
    kategoriId: 1,
    kategoriLabel: "Tokoh Agama",
    pengaruh: "Tinggi",
    alamat: "Jl. Pesantren Al-Ikhlas No. 12, RT 02/RW 01",
    kecamatan: "Cileunyi",
    desa: "Cileunyi Kulon",
    dukungan: "Mendukung",
    estimasiBasisMassa: 420,
    pekerjaan: "Ketua DKM",
    noTelpon: "0812-1000-0001",
    createdAt: "2026-08-10T08:00:00Z",
  },
  {
    id: 2,
    nama: "Ustadz Maman Firmansyah",
    kategoriId: 1,
    kategoriLabel: "Tokoh Agama",
    pengaruh: "Tinggi",
    alamat: "Jl. Pesantren No. 4, RT 02/RW 01",
    kecamatan: "Cileunyi",
    desa: "Cinunuk",
    dukungan: "Mendukung",
    estimasiBasisMassa: 380,
    pekerjaan: "Pengasuh Pesantren",
    noTelpon: "0812-1000-0002",
    createdAt: "2026-08-10T08:10:00Z",
  },
  {
    id: 3,
    nama: "Pdt. Yohanes Simanjuntak",
    kategoriId: 1,
    kategoriLabel: "Tokoh Agama",
    pengaruh: "Sedang",
    alamat: "Jl. Gereja Betlehem No. 7, RT 04/RW 02",
    kecamatan: "Cileunyi",
    desa: "Cileunyi Wetan",
    dukungan: "Netral",
    estimasiBasisMassa: 150,
    pekerjaan: "Pendeta",
    noTelpon: "0812-1000-0003",
    createdAt: "2026-08-11T09:00:00Z",
  },
  {
    id: 4,
    nama: "H. Wawan Ridwan",
    kategoriId: 1,
    kategoriLabel: "Tokoh Agama",
    pengaruh: "Tinggi",
    alamat: "Jl. Masjid Jami No. 3, RT 01/RW 02",
    kecamatan: "Cileunyi",
    desa: "Cimekar",
    dukungan: "Mendukung",
    estimasiBasisMassa: 300,
    pekerjaan: "Imam Masjid",
    noTelpon: "0812-1000-0004",
    createdAt: "2026-08-11T09:10:00Z",
  },
  {
    id: 5,
    nama: "Kang Deni Kurniawan",
    kategoriId: 2,
    kategoriLabel: "Tokoh Pemuda",
    pengaruh: "Sedang",
    alamat: "Jl. Karang Taruna No. 15, RT 03/RW 04",
    kecamatan: "Cileunyi",
    desa: "Cileunyi Kulon",
    dukungan: "Mendukung",
    estimasiBasisMassa: 250,
    pekerjaan: "Ketua Karang Taruna",
    noTelpon: "0812-1000-0005",
    createdAt: "2026-08-12T08:00:00Z",
  },
  {
    id: 6,
    nama: "Rian Hidayatullah",
    kategoriId: 2,
    kategoriLabel: "Tokoh Pemuda",
    pengaruh: "Sedang",
    alamat: "Jl. Pemuda No. 9, RT 02/RW 03",
    kecamatan: "Cileunyi",
    desa: "Cinunuk",
    dukungan: "Mendukung",
    estimasiBasisMassa: 210,
    pekerjaan: "Ketua Pemuda Masjid",
    noTelpon: "0812-1000-0006",
    createdAt: "2026-08-12T08:20:00Z",
  },
  {
    id: 7,
    nama: "Fajar Nugraha",
    kategoriId: 2,
    kategoriLabel: "Tokoh Pemuda",
    pengaruh: "Rendah",
    alamat: "Gg. Motor No. 3, RT 05/RW 02",
    kecamatan: "Cileunyi",
    desa: "Cileunyi Wetan",
    dukungan: "Netral",
    estimasiBasisMassa: 130,
    pekerjaan: "Ketua Komunitas Motor",
    noTelpon: "0812-1000-0007",
    createdAt: "2026-08-12T08:40:00Z",
  },
  {
    id: 8,
    nama: "Yayat Ruhiat",
    kategoriId: 3,
    kategoriLabel: "Tokoh Adat",
    pengaruh: "Sedang",
    alamat: "Kp. Cilame No. 11, RT 04/RW 01",
    kecamatan: "Cileunyi",
    desa: "Cileunyi Kulon",
    dukungan: "Mendukung",
    estimasiBasisMassa: 180,
    pekerjaan: "Sesepuh Kampung",
    noTelpon: "0812-1000-0008",
    createdAt: "2026-08-13T08:00:00Z",
  },
  {
    id: 9,
    nama: "Mak Uwo Iyos",
    kategoriId: 3,
    kategoriLabel: "Tokoh Adat",
    pengaruh: "Rendah",
    alamat: "Kp. Cibiru No. 6, RT 03/RW 02",
    kecamatan: "Cileunyi",
    desa: "Cinunuk",
    dukungan: "Netral",
    estimasiBasisMassa: 140,
    pekerjaan: "Sesepuh Adat",
    noTelpon: null,
    createdAt: "2026-08-13T08:20:00Z",
  },
  {
    id: 10,
    nama: "Abah Endin Sukanda",
    kategoriId: 3,
    kategoriLabel: "Tokoh Adat",
    pengaruh: "Rendah",
    alamat: "Kp. Cimekar No. 2, RT 01/RW 03",
    kecamatan: "Cileunyi",
    desa: "Cimekar",
    dukungan: "Lawan",
    estimasiBasisMassa: 90,
    pekerjaan: "Sesepuh Kampung",
    noTelpon: null,
    createdAt: "2026-08-13T08:40:00Z",
  },
  {
    id: 11,
    nama: "Dra. Siti Aminah",
    kategoriId: 4,
    kategoriLabel: "Tokoh Pendidikan",
    pengaruh: "Sedang",
    alamat: "Jl. Pendidikan No. 21, RT 01/RW 03",
    kecamatan: "Cileunyi",
    desa: "Cileunyi Kulon",
    dukungan: "Mendukung",
    estimasiBasisMassa: 260,
    pekerjaan: "Kepala Sekolah",
    noTelpon: "0812-1000-0011",
    createdAt: "2026-08-14T08:00:00Z",
  },
  {
    id: 12,
    nama: "Drs. Bambang Suherman",
    kategoriId: 4,
    kategoriLabel: "Tokoh Pendidikan",
    pengaruh: "Sedang",
    alamat: "Jl. Madrasah No. 5, RT 02/RW 01",
    kecamatan: "Cileunyi",
    desa: "Cinunuk",
    dukungan: "Netral",
    estimasiBasisMassa: 170,
    pekerjaan: "Kepala Madrasah",
    noTelpon: "0812-1000-0012",
    createdAt: "2026-08-14T08:20:00Z",
  },
  {
    id: 13,
    nama: "Nur Halimah, S.Pd",
    kategoriId: 4,
    kategoriLabel: "Tokoh Pendidikan",
    pengaruh: "Rendah",
    alamat: "Jl. SMA Negeri No. 1, RT 03/RW 02",
    kecamatan: "Cileunyi",
    desa: "Cileunyi Wetan",
    dukungan: "Lawan",
    estimasiBasisMassa: 110,
    pekerjaan: "Guru SMA",
    noTelpon: "0812-1000-0013",
    createdAt: "2026-08-14T08:40:00Z",
  },
  {
    id: 14,
    nama: "Ibu Rosa Damayanti",
    kategoriId: 5,
    kategoriLabel: "Tokoh Perempuan",
    pengaruh: "Tinggi",
    alamat: "Jl. PKK No. 8, RT 02/RW 04",
    kecamatan: "Cileunyi",
    desa: "Cileunyi Kulon",
    dukungan: "Mendukung",
    estimasiBasisMassa: 300,
    pekerjaan: "Ketua PKK",
    noTelpon: "0812-1000-0014",
    createdAt: "2026-08-15T08:00:00Z",
  },
  {
    id: 15,
    nama: "Ibu Neneng Kartika",
    kategoriId: 5,
    kategoriLabel: "Tokoh Perempuan",
    pengaruh: "Sedang",
    alamat: "Jl. Posyandu No. 3, RT 01/RW 02",
    kecamatan: "Cileunyi",
    desa: "Cinunuk",
    dukungan: "Netral",
    estimasiBasisMassa: 160,
    pekerjaan: "Ketua Posyandu",
    noTelpon: "0812-1000-0015",
    createdAt: "2026-08-15T08:20:00Z",
  },
  {
    id: 16,
    nama: "Ibu Titin Suhartini",
    kategoriId: 5,
    kategoriLabel: "Tokoh Perempuan",
    pengaruh: "Rendah",
    alamat: "Jl. Majelis Taklim No. 6, RT 04/RW 01",
    kecamatan: "Cileunyi",
    desa: "Cileunyi Wetan",
    dukungan: "Lawan",
    estimasiBasisMassa: 100,
    pekerjaan: "Ketua Majelis Taklim",
    noTelpon: null,
    createdAt: "2026-08-15T08:40:00Z",
  },
  {
    id: 17,
    nama: "Ust. Zainal Abidin",
    kategoriId: 1,
    kategoriLabel: "Tokoh Agama",
    pengaruh: "Tinggi",
    alamat: "Jl. Majelis Taklim Nurul Iman No. 10, RT 02/RW 02",
    kecamatan: "Cileunyi",
    desa: "Cinunuk",
    dukungan: "Mendukung",
    estimasiBasisMassa: 340,
    pekerjaan: "Pengurus Majelis Taklim",
    noTelpon: "0812-1000-0017",
    createdAt: "2026-08-16T08:00:00Z",
  },
  {
    id: 18,
    nama: "Cecep Iskandar",
    kategoriId: 2,
    kategoriLabel: "Tokoh Pemuda",
    pengaruh: "Sedang",
    alamat: "Jl. Pemuda Desa No. 14, RT 02/RW 03",
    kecamatan: "Cileunyi",
    desa: "Cimekar",
    dukungan: "Mendukung",
    estimasiBasisMassa: 190,
    pekerjaan: "Ketua Pemuda Desa",
    noTelpon: "0812-1000-0018",
    createdAt: "2026-08-16T08:20:00Z",
  },
];

let mockTokohList: Tokoh[] = [...MOCK_TOKOH];
let mockTokohNextId = 1000;

// Tanpa param — unpaginated, sama pola dengan fetchDtdoorAll() (agregasi
// client-side di screen, bukan server-side). Dataset tokoh diharapkan jauh
// lebih kecil dari DPT/Dtdoor, jadi tidak butuh pagination.
async function fetchTokohListMock(): Promise<Tokoh[]> {
  await mockDelay();
  return mockTokohList;
}

export async function fetchTokohList(): Promise<Tokoh[]> {
  if (isMockApiEnabled()) return fetchTokohListMock();
  throw new Error(ENDPOINT_NOT_CONFIRMED);
}

async function createTokohMock(input: CreateTokohInput): Promise<Tokoh> {
  await mockDelay();
  const kategoriLabel = TOKOH_KATEGORI_OPTIONS.find((option) => option.id === input.kategoriId)?.label ?? "Tokoh";
  const created: Tokoh = {
    id: mockTokohNextId++,
    nama: input.nama,
    kategoriId: input.kategoriId,
    kategoriLabel,
    pengaruh: input.pengaruh,
    alamat: input.alamat,
    kecamatan: input.kecamatan,
    desa: input.desa,
    dukungan: input.dukungan,
    estimasiBasisMassa: input.estimasiBasisMassa,
    pekerjaan: input.pekerjaan ?? null,
    noTelpon: input.noTelpon ?? null,
    createdAt: new Date().toISOString(),
  };
  mockTokohList = [created, ...mockTokohList];
  return created;
}

export async function createTokoh(input: CreateTokohInput): Promise<Tokoh> {
  if (isMockApiEnabled()) return createTokohMock(input);
  throw new Error(ENDPOINT_NOT_CONFIRMED);
}
